# whenever we install new dependencies, package-lock.json file is changed, we need to use this so that that dependency is automatically cached
# we will use a dynamic key to do this

name: Caching and Artifacts
on:
  workflow_dispatch:

jobs:
  use-axios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache node modules
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm # this is where we need to cache for macos or ubuntu
        #   dynamic key
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }} # == Linux-npm-cache-79834 (some hash)
          # whenever we install more dependencies, the above hash will change the key, so we will install older cache instead, and once our workflow is done, we will create a new cache with out new hash
          restore-keys: | # if we don't have a cache that matches the above key, we cna provide other keya that we can search for
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-
        #   key: "npm-cache" # this key will be used to retrieve the cache, this is a static key with no variables installed
      # the above step will create an output
      - name: Display cache outputs
        run: echo '${{ toJSON(steps.cache-dependencies.outputs) }}'
      - name: Install dependencies
        run: npm install
      - name: Use axios # axios is a library you can use to send requests
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios');
            const res = await axios('https://icanhazdadjoke.com/', { headers: { Accept: 'text/plain' } })
            console.log(res.data)