name: Checkout
on: [push]

# secrets.GITHUB_TOKEN <- token generated for you and has the access to your repository
# to get files from our repo on to the runner vm

jobs:
  checkout-using-action:
    runs-ons: ubuntu-latest
    steps:
      - name: List of files before
        runs: ls -a
      - name: Checkout using action
        uses: actions/checkout@v4
      - name: List of files after
        runs: ls -a
  checkout-and-display-files:
    runs-on: ubuntu-latest
    steps:
      - name: List files before
        run: ls -a
      - name: Checkout
        run: | # | <- this is the pipe character
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main
        # main branch downloaded in our working directory (this is hardcoded, what if we want to change some
        # different branch)
      - name: List files after
        run: ls -a