name: Concurrency 1
# the concurrency key can be at the workflow level or at the job level
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment"
        type: environment
        required: true
concurrency:
#   group: concurrency-1 # concurrency group
  group: ${{ github.events.inputs.environment }}
  cancel-in-progress: true
# if multiple workflows haev same concurrency group then they won't run at the same time
jobs:
  sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30