name: Repository Events
# to check for what causes the wf to trigger by default (activity types) (for example for pull_request) check the website
# on: [push, pull_request, issues]
# pull_request_target: when we want the wf to trigger for the base branch when a pull_request is made (opened for example)
# if you want to do testing or deploying, then pull_request should be used

on:
  push:
  pull_request:
    types: [opened, assigned, reopened, synchronize]
  issues:
    types: [opened]

# for more info on diff kinds of events: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows
# GITHUB_SHA and GITHUB_REF are environment variable that provide imp context about the specific run and the repo's state
# first one represents the commit hash (SHA) of the commit that triggered the workflow
# eg. GITHUB_SHA=6a2b46c8050ae3fbd7f8bcd7a517cdb2872e54b3
# second one repreents the git reference (branch or tag) that triggered the workflow
# eg. GITHUB_REF=refs/heads/main or GITHUB_REF=refs/tags/v1.0.0

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v4