name: Expressions and Contexts
run-name: Expressions and Contexts by Me
on:
  - push
  - pull_request
  - issues
  - workflow_dispatch

# expressions are not case sensitive: string == String, this is true
# steps.expressions (steps.id of some other step)

jobs:
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string.' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}
      - name: Dump Contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'s
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'