# have to run on the default branch (in our case 'main')
name: External Events
on:
  repository_dispatch:

jobs:
  echo-a-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Repository Dispatch"