name: First Workflow
on: [push]

jobs:
  run-shell-commands: # this is the job id
    runs-on: ubuntu-latest # the default shell is bash, for windows its powershell
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: echo another string
        run: echo "Another string"
      - name: third echo
        run: echo "Third string"
      - name: ls -l
        run: ls -l
      - name: Multiline commands
        run: |
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View software version
        run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: echo a string
        run: Write-Output "Windows string"
      - name: Error step
        run: cmddoesnotexist
