# instead of an event triggering a workflow, we can also trigger it manually
name: Manuallt Triggered
on:
  workflow_dispatch:

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF