name: Matrix
on: [push]

# in order to use different node versions, we can use actions/setup-node (this is an official action)
# we also have similar actions for different languages like python

jobs:
  node-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # now our matrix is three dimensional
        node-version: [14, 15, 16] # here node-version is an arbitary key
    runs-on: ${{ matrix.os }} # ${{}} <- a context
    steps:
      - run: node -v
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: ${{ matrix.node-version }} # our job will run three times for the three values
      - run: node -v
      