name: Status Check Functions
on: [push]

# failure() is a status check function
# success() is not needed, its the deafult behaviour
# only steps.step-2.conclusion == 'failure' won't work, we need to add failure() && steps.step-2.conclusion == 'failure'

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 90 # 20 seconds
        timeout-minutes: 1 # if this step takes longer than 60 secs than it fails
      - name: Step 2
        id: step-2
        continue-on-error: true
        run: exit 1
      - name: Runs on Step-2 Failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo "Step-2 has failed"
      - name: Runs on Failure
        if: failure()
        run: echo "Failure"
      - name: Runs on Success
        # This if condition is not needed (DEFAULT BEHAVIOUR)
        if: success()
        run: echo "Runs only on success"
      - name: Always Runs
        if: always()
        # if: success() || failure()
        run: echo "Always runs"
      - name: Runs when Cancelled
        if: cancelled()
        run: echo "Runs on cancelled"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo "Job 2"