name: Variables and Secrets
on: [push]

# in vars we will have all env vars available
# secrets are encrypted while variables are not
# secret at env level will override secret at repo level (if we use an env), and secret at repo level will 
# override secret at org level (ofcourse assuming that they all have the same name)
# we can do vars.<name of already defined var>
# we can do secrets.<name of already defined secret>

jobs:
  log-vars:
    runs-on: ubuntu-latest
    environment: "Staging"
    env:
      BOOLEAN_SECERT: ${{ secrets.BOOLEAN_SECERT }}
      ENV_LEVEL_VAR: ${{ vars.ENV_LEVEL_VAR }}
      REPO_LEVEL_VAR: ${{ vars.REPO_LEVEL_VAR }}
    steps:
      - name: Run only if BOOLEAN_SECRET is true
        # we have to use env.BOOLEAN_SECERT in if, we can't use $BOOLEAN_SECRET
        if: env.BOOLEAN_SECERT == 'true'
        run: echo "I ran."
      - name: Log Vars
        run: |
          echo "REPO_LEVEL_VAR: $REPO_LEVEL_VAR"
          echo "ENV_LEVEL_VAR: $ENV_LEVEL_VAR"