name: Workflow Commands
on: [push]

# documentation for workflow commands: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Setting an error message
        run: echo "::error::Missing semicolon" # sending a message from our workflow to the runner machine
        # that there is an error
      - name: Setting an error message with a parameter
        run: echo "::error title = Error title, file = app.js, line = 2, endLine = 3, col = 5, endColumn = 7::Missing semicolon"
      - name: Setting a debug message with a parameter
        run: echo "::debug title = Debug title, file = app.js, line = 2, endLine = 3, col = 5, endColumn = 7::Missing semicolon"
      - name: Setting a warning message with a parameter
        run: echo "::warning title = Warning title, file = app.js, line = 2, endLine = 3, col = 5, endColumn = 7::Missing semicolon"
      - name: Setting a notice message with a parameter
        run: echo "::notice title = Notice title, file = app.js, line = 2, endLine = 3, col = 5, endColumn = 7::Missing semicolon"
      - name: Group of logs
        run: |
          echo "::group::Group title"
          echo "Inside group 1"
          echo "Inside group 2"
          echo "::endgroup::"
          echo "Outside group"
      - name: Masking a value
        run: echo "::add-mask::Secret string"
      - name: Echo a secret
        run: echo "Secret string"