name: Working Dir and Shells
on: [push]

# changing default shell

# default shell: bash in linux (ubuntu), powershell (pwsh) in windows

defaults:
  run:
    shell: bash
    # we can also change the working directory (as long as the directory exists ofcourse)
    # working-directory: /de/ed

# GITHUB_SHA - this is an environment variable which displays the id of the commit
# shell table - https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

jobs:
  display-wb-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display working dir and list files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change working directory
        working-directory: /home/runner
        run: pwd
  display-wb-info-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Display working dir and list files
        run: |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name: Python shell
        shell: python
        run: |
          import platform
          print(platform.processor())