# running a workflow based on another workflow: using workflow-run
# we can only have upto three levels of testing

name: Workflow Run
on:
  workflow_run:
    workflows: [Repository Events]
    types: [completed]
jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered because 'Repository Events' was compeleted"